# Perfil PROD — somente COMPORTAMENTO. Valores/segredos vem de env vars reais.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
